sudo: false
branches:
  only:
    - master
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH="$HOME/.yarn/bin:$PATH"
cache:
  yarn: true
language: node_js
node_js:
  - 8.10.0
script:
  - npm test
  - npm run build
# matrix:
#   include:
#     - env: PUMPUP_PROJECT=api
#     - env: PUMPUP_PROJECT=api
# notifications:
#   slack:
#     secure: QXgRXNv666u3DAD8Bn8egZ7RTl0hZKRFitD8EIJUDH2XZyBwuIS8ndzzJv7OB//aFt421WrmISLY00btJGnwGfxDn+HcBvzPDwRt3zWRsyyuKWhu1s1hyxBqS6QIM271r6vd669BAWl0zhiYVLpTorIadHRf1bRIIiVLFDfECdU=
