// flow-typed signature: dfa56caf328fc2854acf42a95a0719e8
// flow-typed version: <<STUB>>/browser-image-resizer_v^2.0.1/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'browser-image-resizer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'browser-image-resizer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'browser-image-resizer/dist/index' {
  declare module.exports: any;
}

declare module 'browser-image-resizer/src/exif' {
  declare module.exports: any;
}

declare module 'browser-image-resizer/src/index' {
  declare module.exports: any;
}

declare module 'browser-image-resizer/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'browser-image-resizer/dist/index.js' {
  declare module.exports: $Exports<'browser-image-resizer/dist/index'>;
}
declare module 'browser-image-resizer/src/exif.js' {
  declare module.exports: $Exports<'browser-image-resizer/src/exif'>;
}
declare module 'browser-image-resizer/src/index.js' {
  declare module.exports: $Exports<'browser-image-resizer/src/index'>;
}
declare module 'browser-image-resizer/webpack.config.js' {
  declare module.exports: $Exports<'browser-image-resizer/webpack.config'>;
}
