// flow-typed signature: 2cb1ed2c8af49b63d85457971a40a440
// flow-typed version: <<STUB>>/emotion-normalize_v^10.0.0/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'emotion-normalize'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'emotion-normalize' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'emotion-normalize/dist' {
  declare module.exports: any;
}

declare module 'emotion-normalize/src' {
  declare module.exports: any;
}

// Filename aliases
declare module 'emotion-normalize/dist/index' {
  declare module.exports: $Exports<'emotion-normalize/dist'>;
}
declare module 'emotion-normalize/dist/index.js' {
  declare module.exports: $Exports<'emotion-normalize/dist'>;
}
declare module 'emotion-normalize/src/index' {
  declare module.exports: $Exports<'emotion-normalize/src'>;
}
declare module 'emotion-normalize/src/index.js' {
  declare module.exports: $Exports<'emotion-normalize/src'>;
}
