// flow-typed signature: 126844535740cc8236740ef97926ebbe
// flow-typed version: <<STUB>>/ethereumjs-util_v^6.1.0/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ethereumjs-util'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ethereumjs-util' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ethereumjs-util/dist/account' {
  declare module.exports: any;
}

declare module 'ethereumjs-util/dist/bytes' {
  declare module.exports: any;
}

declare module 'ethereumjs-util/dist/constants' {
  declare module.exports: any;
}

declare module 'ethereumjs-util/dist/hash' {
  declare module.exports: any;
}

declare module 'ethereumjs-util/dist' {
  declare module.exports: any;
}

declare module 'ethereumjs-util/dist/object' {
  declare module.exports: any;
}

declare module 'ethereumjs-util/dist/signature' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ethereumjs-util/dist/account.js' {
  declare module.exports: $Exports<'ethereumjs-util/dist/account'>;
}
declare module 'ethereumjs-util/dist/bytes.js' {
  declare module.exports: $Exports<'ethereumjs-util/dist/bytes'>;
}
declare module 'ethereumjs-util/dist/constants.js' {
  declare module.exports: $Exports<'ethereumjs-util/dist/constants'>;
}
declare module 'ethereumjs-util/dist/hash.js' {
  declare module.exports: $Exports<'ethereumjs-util/dist/hash'>;
}
declare module 'ethereumjs-util/dist/index' {
  declare module.exports: $Exports<'ethereumjs-util/dist'>;
}
declare module 'ethereumjs-util/dist/index.js' {
  declare module.exports: $Exports<'ethereumjs-util/dist'>;
}
declare module 'ethereumjs-util/dist/object.js' {
  declare module.exports: $Exports<'ethereumjs-util/dist/object'>;
}
declare module 'ethereumjs-util/dist/signature.js' {
  declare module.exports: $Exports<'ethereumjs-util/dist/signature'>;
}
