// flow-typed signature: 15995351fe3ebec099a58665f9aa857f
// flow-typed version: <<STUB>>/firebaseui_v^3.5.2/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'firebaseui'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'firebaseui' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'firebaseui/dist/externs/firebaseui-externs' {
  declare module.exports: any;
}

declare module 'firebaseui/dist/firebaseui' {
  declare module.exports: any;
}

declare module 'firebaseui/dist/npm' {
  declare module.exports: any;
}

// Filename aliases
declare module 'firebaseui/dist/externs/firebaseui-externs.js' {
  declare module.exports: $Exports<'firebaseui/dist/externs/firebaseui-externs'>;
}
declare module 'firebaseui/dist/firebaseui.js' {
  declare module.exports: $Exports<'firebaseui/dist/firebaseui'>;
}
declare module 'firebaseui/dist/npm.js' {
  declare module.exports: $Exports<'firebaseui/dist/npm'>;
}
