// flow-typed signature: 134ac1d809533467c6883f948be4b3a5
// flow-typed version: <<STUB>>/firebase-admin_v^8.9.2/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'firebase-admin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'firebase-admin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'firebase-admin/lib/auth/action-code-settings-builder' {
  declare module.exports: any;
}

declare module 'firebase-admin/lib/auth/auth-api-request' {
  declare module.exports: any;
}

declare module 'firebase-admin/lib/auth/auth-config' {
  declare module.exports: any;
}

declare module 'firebase-admin/lib/auth/auth' {
  declare module.exports: any;
}

declare module 'firebase-admin/lib/auth/credential' {
  declare module.exports: any;
}

declare module 'firebase-admin/lib/auth/tenant-manager' {
  declare module.exports: any;
}

declare module 'firebase-admin/lib/auth/tenant' {
  declare module.exports: any;
}

declare module 'firebase-admin/lib/auth/token-generator' {
  declare module.exports: any;
}

declare module 'firebase-admin/lib/auth/token-verifier' {
  declare module.exports: any;
}

declare module 'firebase-admin/lib/auth/user-import-builder' {
  declare module.exports: any;
}

declare module 'firebase-admin/lib/auth/user-record' {
  declare module.exports: any;
}

declare module 'firebase-admin/lib/database/database' {
  declare module.exports: any;
}

declare module 'firebase-admin/lib/default-namespace' {
  declare module.exports: any;
}

declare module 'firebase-admin/lib/firebase-app' {
  declare module.exports: any;
}

declare module 'firebase-admin/lib/firebase-namespace' {
  declare module.exports: any;
}

declare module 'firebase-admin/lib/firebase-service' {
  declare module.exports: any;
}

declare module 'firebase-admin/lib/firestore/firestore' {
  declare module.exports: any;
}

declare module 'firebase-admin/lib/index' {
  declare module.exports: any;
}

declare module 'firebase-admin/lib/instance-id/instance-id-request' {
  declare module.exports: any;
}

declare module 'firebase-admin/lib/instance-id/instance-id' {
  declare module.exports: any;
}

declare module 'firebase-admin/lib/messaging/batch-request' {
  declare module.exports: any;
}

declare module 'firebase-admin/lib/messaging/messaging-api-request' {
  declare module.exports: any;
}

declare module 'firebase-admin/lib/messaging/messaging-errors' {
  declare module.exports: any;
}

declare module 'firebase-admin/lib/messaging/messaging-types' {
  declare module.exports: any;
}

declare module 'firebase-admin/lib/messaging/messaging' {
  declare module.exports: any;
}

declare module 'firebase-admin/lib/project-management/android-app' {
  declare module.exports: any;
}

declare module 'firebase-admin/lib/project-management/app-metadata' {
  declare module.exports: any;
}

declare module 'firebase-admin/lib/project-management/ios-app' {
  declare module.exports: any;
}

declare module 'firebase-admin/lib/project-management/project-management-api-request' {
  declare module.exports: any;
}

declare module 'firebase-admin/lib/project-management/project-management' {
  declare module.exports: any;
}

declare module 'firebase-admin/lib/security-rules/security-rules-api-client' {
  declare module.exports: any;
}

declare module 'firebase-admin/lib/security-rules/security-rules-utils' {
  declare module.exports: any;
}

declare module 'firebase-admin/lib/security-rules/security-rules' {
  declare module.exports: any;
}

declare module 'firebase-admin/lib/storage/storage' {
  declare module.exports: any;
}

declare module 'firebase-admin/lib/utils/api-request' {
  declare module.exports: any;
}

declare module 'firebase-admin/lib/utils/deep-copy' {
  declare module.exports: any;
}

declare module 'firebase-admin/lib/utils/error' {
  declare module.exports: any;
}

declare module 'firebase-admin/lib/utils/index' {
  declare module.exports: any;
}

declare module 'firebase-admin/lib/utils/validator' {
  declare module.exports: any;
}

// Filename aliases
declare module 'firebase-admin/lib/auth/action-code-settings-builder.js' {
  declare module.exports: $Exports<'firebase-admin/lib/auth/action-code-settings-builder'>;
}
declare module 'firebase-admin/lib/auth/auth-api-request.js' {
  declare module.exports: $Exports<'firebase-admin/lib/auth/auth-api-request'>;
}
declare module 'firebase-admin/lib/auth/auth-config.js' {
  declare module.exports: $Exports<'firebase-admin/lib/auth/auth-config'>;
}
declare module 'firebase-admin/lib/auth/auth.js' {
  declare module.exports: $Exports<'firebase-admin/lib/auth/auth'>;
}
declare module 'firebase-admin/lib/auth/credential.js' {
  declare module.exports: $Exports<'firebase-admin/lib/auth/credential'>;
}
declare module 'firebase-admin/lib/auth/tenant-manager.js' {
  declare module.exports: $Exports<'firebase-admin/lib/auth/tenant-manager'>;
}
declare module 'firebase-admin/lib/auth/tenant.js' {
  declare module.exports: $Exports<'firebase-admin/lib/auth/tenant'>;
}
declare module 'firebase-admin/lib/auth/token-generator.js' {
  declare module.exports: $Exports<'firebase-admin/lib/auth/token-generator'>;
}
declare module 'firebase-admin/lib/auth/token-verifier.js' {
  declare module.exports: $Exports<'firebase-admin/lib/auth/token-verifier'>;
}
declare module 'firebase-admin/lib/auth/user-import-builder.js' {
  declare module.exports: $Exports<'firebase-admin/lib/auth/user-import-builder'>;
}
declare module 'firebase-admin/lib/auth/user-record.js' {
  declare module.exports: $Exports<'firebase-admin/lib/auth/user-record'>;
}
declare module 'firebase-admin/lib/database/database.js' {
  declare module.exports: $Exports<'firebase-admin/lib/database/database'>;
}
declare module 'firebase-admin/lib/default-namespace.js' {
  declare module.exports: $Exports<'firebase-admin/lib/default-namespace'>;
}
declare module 'firebase-admin/lib/firebase-app.js' {
  declare module.exports: $Exports<'firebase-admin/lib/firebase-app'>;
}
declare module 'firebase-admin/lib/firebase-namespace.js' {
  declare module.exports: $Exports<'firebase-admin/lib/firebase-namespace'>;
}
declare module 'firebase-admin/lib/firebase-service.js' {
  declare module.exports: $Exports<'firebase-admin/lib/firebase-service'>;
}
declare module 'firebase-admin/lib/firestore/firestore.js' {
  declare module.exports: $Exports<'firebase-admin/lib/firestore/firestore'>;
}
declare module 'firebase-admin/lib/index.js' {
  declare module.exports: $Exports<'firebase-admin/lib/index'>;
}
declare module 'firebase-admin/lib/instance-id/instance-id-request.js' {
  declare module.exports: $Exports<'firebase-admin/lib/instance-id/instance-id-request'>;
}
declare module 'firebase-admin/lib/instance-id/instance-id.js' {
  declare module.exports: $Exports<'firebase-admin/lib/instance-id/instance-id'>;
}
declare module 'firebase-admin/lib/messaging/batch-request.js' {
  declare module.exports: $Exports<'firebase-admin/lib/messaging/batch-request'>;
}
declare module 'firebase-admin/lib/messaging/messaging-api-request.js' {
  declare module.exports: $Exports<'firebase-admin/lib/messaging/messaging-api-request'>;
}
declare module 'firebase-admin/lib/messaging/messaging-errors.js' {
  declare module.exports: $Exports<'firebase-admin/lib/messaging/messaging-errors'>;
}
declare module 'firebase-admin/lib/messaging/messaging-types.js' {
  declare module.exports: $Exports<'firebase-admin/lib/messaging/messaging-types'>;
}
declare module 'firebase-admin/lib/messaging/messaging.js' {
  declare module.exports: $Exports<'firebase-admin/lib/messaging/messaging'>;
}
declare module 'firebase-admin/lib/project-management/android-app.js' {
  declare module.exports: $Exports<'firebase-admin/lib/project-management/android-app'>;
}
declare module 'firebase-admin/lib/project-management/app-metadata.js' {
  declare module.exports: $Exports<'firebase-admin/lib/project-management/app-metadata'>;
}
declare module 'firebase-admin/lib/project-management/ios-app.js' {
  declare module.exports: $Exports<'firebase-admin/lib/project-management/ios-app'>;
}
declare module 'firebase-admin/lib/project-management/project-management-api-request.js' {
  declare module.exports: $Exports<'firebase-admin/lib/project-management/project-management-api-request'>;
}
declare module 'firebase-admin/lib/project-management/project-management.js' {
  declare module.exports: $Exports<'firebase-admin/lib/project-management/project-management'>;
}
declare module 'firebase-admin/lib/security-rules/security-rules-api-client.js' {
  declare module.exports: $Exports<'firebase-admin/lib/security-rules/security-rules-api-client'>;
}
declare module 'firebase-admin/lib/security-rules/security-rules-utils.js' {
  declare module.exports: $Exports<'firebase-admin/lib/security-rules/security-rules-utils'>;
}
declare module 'firebase-admin/lib/security-rules/security-rules.js' {
  declare module.exports: $Exports<'firebase-admin/lib/security-rules/security-rules'>;
}
declare module 'firebase-admin/lib/storage/storage.js' {
  declare module.exports: $Exports<'firebase-admin/lib/storage/storage'>;
}
declare module 'firebase-admin/lib/utils/api-request.js' {
  declare module.exports: $Exports<'firebase-admin/lib/utils/api-request'>;
}
declare module 'firebase-admin/lib/utils/deep-copy.js' {
  declare module.exports: $Exports<'firebase-admin/lib/utils/deep-copy'>;
}
declare module 'firebase-admin/lib/utils/error.js' {
  declare module.exports: $Exports<'firebase-admin/lib/utils/error'>;
}
declare module 'firebase-admin/lib/utils/index.js' {
  declare module.exports: $Exports<'firebase-admin/lib/utils/index'>;
}
declare module 'firebase-admin/lib/utils/validator.js' {
  declare module.exports: $Exports<'firebase-admin/lib/utils/validator'>;
}
