// flow-typed signature: f956b034b9f027f0ed6819d218aa1922
// flow-typed version: <<STUB>>/js-promisify_v^1.3.1/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'js-promisify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'js-promisify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'js-promisify/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'js-promisify/index' {
  declare module.exports: $Exports<'js-promisify'>;
}
declare module 'js-promisify/index.js' {
  declare module.exports: $Exports<'js-promisify'>;
}
declare module 'js-promisify/test/test.js' {
  declare module.exports: $Exports<'js-promisify/test/test'>;
}
