// flow-typed signature: 5cb7c042cacf6f12ae5f518c225e8ef8
// flow-typed version: <<STUB>>/qrious_v^4.0.2/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'qrious'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'qrious' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'qrious/dist/qrious' {
  declare module.exports: any;
}

declare module 'qrious/dist/qrious.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'qrious/dist/qrious.js' {
  declare module.exports: $Exports<'qrious/dist/qrious'>;
}
declare module 'qrious/dist/qrious.min.js' {
  declare module.exports: $Exports<'qrious/dist/qrious.min'>;
}
