// flow-typed signature: 0aff997c6e2744b9ecdfcc7a0876b58d
// flow-typed version: <<STUB>>/react-html5-camera-photo_v^1.2.9/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-html5-camera-photo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-html5-camera-photo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-html5-camera-photo/build' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-html5-camera-photo/build/index' {
  declare module.exports: $Exports<'react-html5-camera-photo/build'>;
}
declare module 'react-html5-camera-photo/build/index.js' {
  declare module.exports: $Exports<'react-html5-camera-photo/build'>;
}
