// flow-typed signature: f332edf30afd8a50d22a01929f9ecfa9
// flow-typed version: <<STUB>>/react-resize-detector_v^3.4.0/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-resize-detector'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-resize-detector' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-resize-detector/lib/esm' {
  declare module.exports: any;
}

declare module 'react-resize-detector/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-resize-detector/lib/esm/index' {
  declare module.exports: $Exports<'react-resize-detector/lib/esm'>;
}
declare module 'react-resize-detector/lib/esm/index.js' {
  declare module.exports: $Exports<'react-resize-detector/lib/esm'>;
}
declare module 'react-resize-detector/lib/index' {
  declare module.exports: $Exports<'react-resize-detector/lib'>;
}
declare module 'react-resize-detector/lib/index.js' {
  declare module.exports: $Exports<'react-resize-detector/lib'>;
}
