// flow-typed signature: d6032ab177209554501e82f3c5a836ca
// flow-typed version: <<STUB>>/react-redux-firebase_v^2.2.6/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-redux-firebase'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-redux-firebase' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-redux-firebase/dist/react-redux-firebase' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/dist/react-redux-firebase.min' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/es/actions/auth' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/es/actions' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/es/actions/query' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/es/actions/storage' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/es/constants' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/es/createFirebaseInstance' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/es/enhancer' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/es/firebaseConnect' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/es/firestoreConnect' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/es/helpers' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/es' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/es/reducer' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/es/reducers' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/es/utils/actions' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/es/utils/auth' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/es/utils/events' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/es/utils' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/es/utils/populate' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/es/utils/query' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/es/utils/reducers' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/es/utils/storage' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/es/withFirebase' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/es/withFirestore' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/lib/actions/auth' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/lib/actions' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/lib/actions/query' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/lib/actions/storage' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/lib/constants' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/lib/createFirebaseInstance' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/lib/enhancer' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/lib/firebaseConnect' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/lib/firestoreConnect' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/lib/helpers' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/lib' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/lib/reducer' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/lib/reducers' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/lib/utils/actions' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/lib/utils/auth' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/lib/utils/events' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/lib/utils' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/lib/utils/populate' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/lib/utils/query' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/lib/utils/reducers' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/lib/utils/storage' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/lib/withFirebase' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/lib/withFirestore' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/src/actions/auth' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/src/actions' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/src/actions/query' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/src/actions/storage' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/src/constants' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/src/createFirebaseInstance' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/src/enhancer' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/src/firebaseConnect' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/src/firestoreConnect' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/src/helpers' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/src' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/src/reducer' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/src/reducers' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/src/utils/actions' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/src/utils/auth' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/src/utils/events' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/src/utils' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/src/utils/populate' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/src/utils/query' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/src/utils/reducers' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/src/utils/storage' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/src/withFirebase' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/src/withFirestore' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/test/mockData' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/test/setup' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/test/unit/actions/auth.spec' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/test/unit/actions/query.spec' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/test/unit/actions/storage.spec' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/test/unit/enhancer.spec' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/test/unit/firebaseConnect.spec' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/test/unit/firestoreConnect.spec' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/test/unit/helpers.spec' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/test/unit/library.spec' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/test/unit/reducer.spec' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/test/unit/utils/actions.spec' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/test/unit/utils/auth.spec' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/test/unit/utils/events.spec' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/test/unit/utils/index.spec' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/test/unit/utils/populate.spec' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/test/unit/utils/query.spec' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/test/unit/utils/storage.spec' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/test/unit/withFirebase.spec' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/test/unit/withFirestore.spec' {
  declare module.exports: any;
}

declare module 'react-redux-firebase/test/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-redux-firebase/dist/react-redux-firebase.js' {
  declare module.exports: $Exports<'react-redux-firebase/dist/react-redux-firebase'>;
}
declare module 'react-redux-firebase/dist/react-redux-firebase.min.js' {
  declare module.exports: $Exports<'react-redux-firebase/dist/react-redux-firebase.min'>;
}
declare module 'react-redux-firebase/es/actions/auth.js' {
  declare module.exports: $Exports<'react-redux-firebase/es/actions/auth'>;
}
declare module 'react-redux-firebase/es/actions/index' {
  declare module.exports: $Exports<'react-redux-firebase/es/actions'>;
}
declare module 'react-redux-firebase/es/actions/index.js' {
  declare module.exports: $Exports<'react-redux-firebase/es/actions'>;
}
declare module 'react-redux-firebase/es/actions/query.js' {
  declare module.exports: $Exports<'react-redux-firebase/es/actions/query'>;
}
declare module 'react-redux-firebase/es/actions/storage.js' {
  declare module.exports: $Exports<'react-redux-firebase/es/actions/storage'>;
}
declare module 'react-redux-firebase/es/constants.js' {
  declare module.exports: $Exports<'react-redux-firebase/es/constants'>;
}
declare module 'react-redux-firebase/es/createFirebaseInstance.js' {
  declare module.exports: $Exports<'react-redux-firebase/es/createFirebaseInstance'>;
}
declare module 'react-redux-firebase/es/enhancer.js' {
  declare module.exports: $Exports<'react-redux-firebase/es/enhancer'>;
}
declare module 'react-redux-firebase/es/firebaseConnect.js' {
  declare module.exports: $Exports<'react-redux-firebase/es/firebaseConnect'>;
}
declare module 'react-redux-firebase/es/firestoreConnect.js' {
  declare module.exports: $Exports<'react-redux-firebase/es/firestoreConnect'>;
}
declare module 'react-redux-firebase/es/helpers.js' {
  declare module.exports: $Exports<'react-redux-firebase/es/helpers'>;
}
declare module 'react-redux-firebase/es/index' {
  declare module.exports: $Exports<'react-redux-firebase/es'>;
}
declare module 'react-redux-firebase/es/index.js' {
  declare module.exports: $Exports<'react-redux-firebase/es'>;
}
declare module 'react-redux-firebase/es/reducer.js' {
  declare module.exports: $Exports<'react-redux-firebase/es/reducer'>;
}
declare module 'react-redux-firebase/es/reducers.js' {
  declare module.exports: $Exports<'react-redux-firebase/es/reducers'>;
}
declare module 'react-redux-firebase/es/utils/actions.js' {
  declare module.exports: $Exports<'react-redux-firebase/es/utils/actions'>;
}
declare module 'react-redux-firebase/es/utils/auth.js' {
  declare module.exports: $Exports<'react-redux-firebase/es/utils/auth'>;
}
declare module 'react-redux-firebase/es/utils/events.js' {
  declare module.exports: $Exports<'react-redux-firebase/es/utils/events'>;
}
declare module 'react-redux-firebase/es/utils/index' {
  declare module.exports: $Exports<'react-redux-firebase/es/utils'>;
}
declare module 'react-redux-firebase/es/utils/index.js' {
  declare module.exports: $Exports<'react-redux-firebase/es/utils'>;
}
declare module 'react-redux-firebase/es/utils/populate.js' {
  declare module.exports: $Exports<'react-redux-firebase/es/utils/populate'>;
}
declare module 'react-redux-firebase/es/utils/query.js' {
  declare module.exports: $Exports<'react-redux-firebase/es/utils/query'>;
}
declare module 'react-redux-firebase/es/utils/reducers.js' {
  declare module.exports: $Exports<'react-redux-firebase/es/utils/reducers'>;
}
declare module 'react-redux-firebase/es/utils/storage.js' {
  declare module.exports: $Exports<'react-redux-firebase/es/utils/storage'>;
}
declare module 'react-redux-firebase/es/withFirebase.js' {
  declare module.exports: $Exports<'react-redux-firebase/es/withFirebase'>;
}
declare module 'react-redux-firebase/es/withFirestore.js' {
  declare module.exports: $Exports<'react-redux-firebase/es/withFirestore'>;
}
declare module 'react-redux-firebase/lib/actions/auth.js' {
  declare module.exports: $Exports<'react-redux-firebase/lib/actions/auth'>;
}
declare module 'react-redux-firebase/lib/actions/index' {
  declare module.exports: $Exports<'react-redux-firebase/lib/actions'>;
}
declare module 'react-redux-firebase/lib/actions/index.js' {
  declare module.exports: $Exports<'react-redux-firebase/lib/actions'>;
}
declare module 'react-redux-firebase/lib/actions/query.js' {
  declare module.exports: $Exports<'react-redux-firebase/lib/actions/query'>;
}
declare module 'react-redux-firebase/lib/actions/storage.js' {
  declare module.exports: $Exports<'react-redux-firebase/lib/actions/storage'>;
}
declare module 'react-redux-firebase/lib/constants.js' {
  declare module.exports: $Exports<'react-redux-firebase/lib/constants'>;
}
declare module 'react-redux-firebase/lib/createFirebaseInstance.js' {
  declare module.exports: $Exports<'react-redux-firebase/lib/createFirebaseInstance'>;
}
declare module 'react-redux-firebase/lib/enhancer.js' {
  declare module.exports: $Exports<'react-redux-firebase/lib/enhancer'>;
}
declare module 'react-redux-firebase/lib/firebaseConnect.js' {
  declare module.exports: $Exports<'react-redux-firebase/lib/firebaseConnect'>;
}
declare module 'react-redux-firebase/lib/firestoreConnect.js' {
  declare module.exports: $Exports<'react-redux-firebase/lib/firestoreConnect'>;
}
declare module 'react-redux-firebase/lib/helpers.js' {
  declare module.exports: $Exports<'react-redux-firebase/lib/helpers'>;
}
declare module 'react-redux-firebase/lib/index' {
  declare module.exports: $Exports<'react-redux-firebase/lib'>;
}
declare module 'react-redux-firebase/lib/index.js' {
  declare module.exports: $Exports<'react-redux-firebase/lib'>;
}
declare module 'react-redux-firebase/lib/reducer.js' {
  declare module.exports: $Exports<'react-redux-firebase/lib/reducer'>;
}
declare module 'react-redux-firebase/lib/reducers.js' {
  declare module.exports: $Exports<'react-redux-firebase/lib/reducers'>;
}
declare module 'react-redux-firebase/lib/utils/actions.js' {
  declare module.exports: $Exports<'react-redux-firebase/lib/utils/actions'>;
}
declare module 'react-redux-firebase/lib/utils/auth.js' {
  declare module.exports: $Exports<'react-redux-firebase/lib/utils/auth'>;
}
declare module 'react-redux-firebase/lib/utils/events.js' {
  declare module.exports: $Exports<'react-redux-firebase/lib/utils/events'>;
}
declare module 'react-redux-firebase/lib/utils/index' {
  declare module.exports: $Exports<'react-redux-firebase/lib/utils'>;
}
declare module 'react-redux-firebase/lib/utils/index.js' {
  declare module.exports: $Exports<'react-redux-firebase/lib/utils'>;
}
declare module 'react-redux-firebase/lib/utils/populate.js' {
  declare module.exports: $Exports<'react-redux-firebase/lib/utils/populate'>;
}
declare module 'react-redux-firebase/lib/utils/query.js' {
  declare module.exports: $Exports<'react-redux-firebase/lib/utils/query'>;
}
declare module 'react-redux-firebase/lib/utils/reducers.js' {
  declare module.exports: $Exports<'react-redux-firebase/lib/utils/reducers'>;
}
declare module 'react-redux-firebase/lib/utils/storage.js' {
  declare module.exports: $Exports<'react-redux-firebase/lib/utils/storage'>;
}
declare module 'react-redux-firebase/lib/withFirebase.js' {
  declare module.exports: $Exports<'react-redux-firebase/lib/withFirebase'>;
}
declare module 'react-redux-firebase/lib/withFirestore.js' {
  declare module.exports: $Exports<'react-redux-firebase/lib/withFirestore'>;
}
declare module 'react-redux-firebase/src/actions/auth.js' {
  declare module.exports: $Exports<'react-redux-firebase/src/actions/auth'>;
}
declare module 'react-redux-firebase/src/actions/index' {
  declare module.exports: $Exports<'react-redux-firebase/src/actions'>;
}
declare module 'react-redux-firebase/src/actions/index.js' {
  declare module.exports: $Exports<'react-redux-firebase/src/actions'>;
}
declare module 'react-redux-firebase/src/actions/query.js' {
  declare module.exports: $Exports<'react-redux-firebase/src/actions/query'>;
}
declare module 'react-redux-firebase/src/actions/storage.js' {
  declare module.exports: $Exports<'react-redux-firebase/src/actions/storage'>;
}
declare module 'react-redux-firebase/src/constants.js' {
  declare module.exports: $Exports<'react-redux-firebase/src/constants'>;
}
declare module 'react-redux-firebase/src/createFirebaseInstance.js' {
  declare module.exports: $Exports<'react-redux-firebase/src/createFirebaseInstance'>;
}
declare module 'react-redux-firebase/src/enhancer.js' {
  declare module.exports: $Exports<'react-redux-firebase/src/enhancer'>;
}
declare module 'react-redux-firebase/src/firebaseConnect.js' {
  declare module.exports: $Exports<'react-redux-firebase/src/firebaseConnect'>;
}
declare module 'react-redux-firebase/src/firestoreConnect.js' {
  declare module.exports: $Exports<'react-redux-firebase/src/firestoreConnect'>;
}
declare module 'react-redux-firebase/src/helpers.js' {
  declare module.exports: $Exports<'react-redux-firebase/src/helpers'>;
}
declare module 'react-redux-firebase/src/index' {
  declare module.exports: $Exports<'react-redux-firebase/src'>;
}
declare module 'react-redux-firebase/src/index.js' {
  declare module.exports: $Exports<'react-redux-firebase/src'>;
}
declare module 'react-redux-firebase/src/reducer.js' {
  declare module.exports: $Exports<'react-redux-firebase/src/reducer'>;
}
declare module 'react-redux-firebase/src/reducers.js' {
  declare module.exports: $Exports<'react-redux-firebase/src/reducers'>;
}
declare module 'react-redux-firebase/src/utils/actions.js' {
  declare module.exports: $Exports<'react-redux-firebase/src/utils/actions'>;
}
declare module 'react-redux-firebase/src/utils/auth.js' {
  declare module.exports: $Exports<'react-redux-firebase/src/utils/auth'>;
}
declare module 'react-redux-firebase/src/utils/events.js' {
  declare module.exports: $Exports<'react-redux-firebase/src/utils/events'>;
}
declare module 'react-redux-firebase/src/utils/index' {
  declare module.exports: $Exports<'react-redux-firebase/src/utils'>;
}
declare module 'react-redux-firebase/src/utils/index.js' {
  declare module.exports: $Exports<'react-redux-firebase/src/utils'>;
}
declare module 'react-redux-firebase/src/utils/populate.js' {
  declare module.exports: $Exports<'react-redux-firebase/src/utils/populate'>;
}
declare module 'react-redux-firebase/src/utils/query.js' {
  declare module.exports: $Exports<'react-redux-firebase/src/utils/query'>;
}
declare module 'react-redux-firebase/src/utils/reducers.js' {
  declare module.exports: $Exports<'react-redux-firebase/src/utils/reducers'>;
}
declare module 'react-redux-firebase/src/utils/storage.js' {
  declare module.exports: $Exports<'react-redux-firebase/src/utils/storage'>;
}
declare module 'react-redux-firebase/src/withFirebase.js' {
  declare module.exports: $Exports<'react-redux-firebase/src/withFirebase'>;
}
declare module 'react-redux-firebase/src/withFirestore.js' {
  declare module.exports: $Exports<'react-redux-firebase/src/withFirestore'>;
}
declare module 'react-redux-firebase/test/mockData.js' {
  declare module.exports: $Exports<'react-redux-firebase/test/mockData'>;
}
declare module 'react-redux-firebase/test/setup.js' {
  declare module.exports: $Exports<'react-redux-firebase/test/setup'>;
}
declare module 'react-redux-firebase/test/unit/actions/auth.spec.js' {
  declare module.exports: $Exports<'react-redux-firebase/test/unit/actions/auth.spec'>;
}
declare module 'react-redux-firebase/test/unit/actions/query.spec.js' {
  declare module.exports: $Exports<'react-redux-firebase/test/unit/actions/query.spec'>;
}
declare module 'react-redux-firebase/test/unit/actions/storage.spec.js' {
  declare module.exports: $Exports<'react-redux-firebase/test/unit/actions/storage.spec'>;
}
declare module 'react-redux-firebase/test/unit/enhancer.spec.js' {
  declare module.exports: $Exports<'react-redux-firebase/test/unit/enhancer.spec'>;
}
declare module 'react-redux-firebase/test/unit/firebaseConnect.spec.js' {
  declare module.exports: $Exports<'react-redux-firebase/test/unit/firebaseConnect.spec'>;
}
declare module 'react-redux-firebase/test/unit/firestoreConnect.spec.js' {
  declare module.exports: $Exports<'react-redux-firebase/test/unit/firestoreConnect.spec'>;
}
declare module 'react-redux-firebase/test/unit/helpers.spec.js' {
  declare module.exports: $Exports<'react-redux-firebase/test/unit/helpers.spec'>;
}
declare module 'react-redux-firebase/test/unit/library.spec.js' {
  declare module.exports: $Exports<'react-redux-firebase/test/unit/library.spec'>;
}
declare module 'react-redux-firebase/test/unit/reducer.spec.js' {
  declare module.exports: $Exports<'react-redux-firebase/test/unit/reducer.spec'>;
}
declare module 'react-redux-firebase/test/unit/utils/actions.spec.js' {
  declare module.exports: $Exports<'react-redux-firebase/test/unit/utils/actions.spec'>;
}
declare module 'react-redux-firebase/test/unit/utils/auth.spec.js' {
  declare module.exports: $Exports<'react-redux-firebase/test/unit/utils/auth.spec'>;
}
declare module 'react-redux-firebase/test/unit/utils/events.spec.js' {
  declare module.exports: $Exports<'react-redux-firebase/test/unit/utils/events.spec'>;
}
declare module 'react-redux-firebase/test/unit/utils/index.spec.js' {
  declare module.exports: $Exports<'react-redux-firebase/test/unit/utils/index.spec'>;
}
declare module 'react-redux-firebase/test/unit/utils/populate.spec.js' {
  declare module.exports: $Exports<'react-redux-firebase/test/unit/utils/populate.spec'>;
}
declare module 'react-redux-firebase/test/unit/utils/query.spec.js' {
  declare module.exports: $Exports<'react-redux-firebase/test/unit/utils/query.spec'>;
}
declare module 'react-redux-firebase/test/unit/utils/storage.spec.js' {
  declare module.exports: $Exports<'react-redux-firebase/test/unit/utils/storage.spec'>;
}
declare module 'react-redux-firebase/test/unit/withFirebase.spec.js' {
  declare module.exports: $Exports<'react-redux-firebase/test/unit/withFirebase.spec'>;
}
declare module 'react-redux-firebase/test/unit/withFirestore.spec.js' {
  declare module.exports: $Exports<'react-redux-firebase/test/unit/withFirestore.spec'>;
}
declare module 'react-redux-firebase/test/utils.js' {
  declare module.exports: $Exports<'react-redux-firebase/test/utils'>;
}
