// flow-typed signature: 3001c518dd920f94aaa99489389afab1
// flow-typed version: <<STUB>>/redux-firestore_v^0.6.3/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-firestore'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-firestore' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-firestore/dist/redux-firestore' {
  declare module.exports: any;
}

declare module 'redux-firestore/dist/redux-firestore.min' {
  declare module.exports: any;
}

declare module 'redux-firestore/es/actions/firestore' {
  declare module.exports: any;
}

declare module 'redux-firestore/es/actions/index' {
  declare module.exports: any;
}

declare module 'redux-firestore/es/constants' {
  declare module.exports: any;
}

declare module 'redux-firestore/es/createFirestoreInstance' {
  declare module.exports: any;
}

declare module 'redux-firestore/es/enhancer' {
  declare module.exports: any;
}

declare module 'redux-firestore/es/index' {
  declare module.exports: any;
}

declare module 'redux-firestore/es/middleware' {
  declare module.exports: any;
}

declare module 'redux-firestore/es/reducer' {
  declare module.exports: any;
}

declare module 'redux-firestore/es/reducers/crossSliceReducer' {
  declare module.exports: any;
}

declare module 'redux-firestore/es/reducers/dataReducer' {
  declare module.exports: any;
}

declare module 'redux-firestore/es/reducers/errorsReducer' {
  declare module.exports: any;
}

declare module 'redux-firestore/es/reducers/index' {
  declare module.exports: any;
}

declare module 'redux-firestore/es/reducers/listenersReducer' {
  declare module.exports: any;
}

declare module 'redux-firestore/es/reducers/orderedReducer' {
  declare module.exports: any;
}

declare module 'redux-firestore/es/reducers/queriesReducer' {
  declare module.exports: any;
}

declare module 'redux-firestore/es/reducers/statusReducer' {
  declare module.exports: any;
}

declare module 'redux-firestore/es/utils/actions' {
  declare module.exports: any;
}

declare module 'redux-firestore/es/utils/query' {
  declare module.exports: any;
}

declare module 'redux-firestore/es/utils/reducers' {
  declare module.exports: any;
}

declare module 'redux-firestore/lib/actions/firestore' {
  declare module.exports: any;
}

declare module 'redux-firestore/lib/actions/index' {
  declare module.exports: any;
}

declare module 'redux-firestore/lib/constants' {
  declare module.exports: any;
}

declare module 'redux-firestore/lib/createFirestoreInstance' {
  declare module.exports: any;
}

declare module 'redux-firestore/lib/enhancer' {
  declare module.exports: any;
}

declare module 'redux-firestore/lib/index' {
  declare module.exports: any;
}

declare module 'redux-firestore/lib/middleware' {
  declare module.exports: any;
}

declare module 'redux-firestore/lib/reducer' {
  declare module.exports: any;
}

declare module 'redux-firestore/lib/reducers/crossSliceReducer' {
  declare module.exports: any;
}

declare module 'redux-firestore/lib/reducers/dataReducer' {
  declare module.exports: any;
}

declare module 'redux-firestore/lib/reducers/errorsReducer' {
  declare module.exports: any;
}

declare module 'redux-firestore/lib/reducers/index' {
  declare module.exports: any;
}

declare module 'redux-firestore/lib/reducers/listenersReducer' {
  declare module.exports: any;
}

declare module 'redux-firestore/lib/reducers/orderedReducer' {
  declare module.exports: any;
}

declare module 'redux-firestore/lib/reducers/queriesReducer' {
  declare module.exports: any;
}

declare module 'redux-firestore/lib/reducers/statusReducer' {
  declare module.exports: any;
}

declare module 'redux-firestore/lib/utils/actions' {
  declare module.exports: any;
}

declare module 'redux-firestore/lib/utils/query' {
  declare module.exports: any;
}

declare module 'redux-firestore/lib/utils/reducers' {
  declare module.exports: any;
}

declare module 'redux-firestore/src/actions/firestore' {
  declare module.exports: any;
}

declare module 'redux-firestore/src/actions/index' {
  declare module.exports: any;
}

declare module 'redux-firestore/src/constants' {
  declare module.exports: any;
}

declare module 'redux-firestore/src/createFirestoreInstance' {
  declare module.exports: any;
}

declare module 'redux-firestore/src/enhancer' {
  declare module.exports: any;
}

declare module 'redux-firestore/src/index' {
  declare module.exports: any;
}

declare module 'redux-firestore/src/middleware' {
  declare module.exports: any;
}

declare module 'redux-firestore/src/reducer' {
  declare module.exports: any;
}

declare module 'redux-firestore/src/reducers/crossSliceReducer' {
  declare module.exports: any;
}

declare module 'redux-firestore/src/reducers/dataReducer' {
  declare module.exports: any;
}

declare module 'redux-firestore/src/reducers/errorsReducer' {
  declare module.exports: any;
}

declare module 'redux-firestore/src/reducers/index' {
  declare module.exports: any;
}

declare module 'redux-firestore/src/reducers/listenersReducer' {
  declare module.exports: any;
}

declare module 'redux-firestore/src/reducers/orderedReducer' {
  declare module.exports: any;
}

declare module 'redux-firestore/src/reducers/queriesReducer' {
  declare module.exports: any;
}

declare module 'redux-firestore/src/reducers/statusReducer' {
  declare module.exports: any;
}

declare module 'redux-firestore/src/utils/actions' {
  declare module.exports: any;
}

declare module 'redux-firestore/src/utils/query' {
  declare module.exports: any;
}

declare module 'redux-firestore/src/utils/reducers' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-firestore/dist/redux-firestore.js' {
  declare module.exports: $Exports<'redux-firestore/dist/redux-firestore'>;
}
declare module 'redux-firestore/dist/redux-firestore.min.js' {
  declare module.exports: $Exports<'redux-firestore/dist/redux-firestore.min'>;
}
declare module 'redux-firestore/es/actions/firestore.js' {
  declare module.exports: $Exports<'redux-firestore/es/actions/firestore'>;
}
declare module 'redux-firestore/es/actions/index.js' {
  declare module.exports: $Exports<'redux-firestore/es/actions/index'>;
}
declare module 'redux-firestore/es/constants.js' {
  declare module.exports: $Exports<'redux-firestore/es/constants'>;
}
declare module 'redux-firestore/es/createFirestoreInstance.js' {
  declare module.exports: $Exports<'redux-firestore/es/createFirestoreInstance'>;
}
declare module 'redux-firestore/es/enhancer.js' {
  declare module.exports: $Exports<'redux-firestore/es/enhancer'>;
}
declare module 'redux-firestore/es/index.js' {
  declare module.exports: $Exports<'redux-firestore/es/index'>;
}
declare module 'redux-firestore/es/middleware.js' {
  declare module.exports: $Exports<'redux-firestore/es/middleware'>;
}
declare module 'redux-firestore/es/reducer.js' {
  declare module.exports: $Exports<'redux-firestore/es/reducer'>;
}
declare module 'redux-firestore/es/reducers/crossSliceReducer.js' {
  declare module.exports: $Exports<'redux-firestore/es/reducers/crossSliceReducer'>;
}
declare module 'redux-firestore/es/reducers/dataReducer.js' {
  declare module.exports: $Exports<'redux-firestore/es/reducers/dataReducer'>;
}
declare module 'redux-firestore/es/reducers/errorsReducer.js' {
  declare module.exports: $Exports<'redux-firestore/es/reducers/errorsReducer'>;
}
declare module 'redux-firestore/es/reducers/index.js' {
  declare module.exports: $Exports<'redux-firestore/es/reducers/index'>;
}
declare module 'redux-firestore/es/reducers/listenersReducer.js' {
  declare module.exports: $Exports<'redux-firestore/es/reducers/listenersReducer'>;
}
declare module 'redux-firestore/es/reducers/orderedReducer.js' {
  declare module.exports: $Exports<'redux-firestore/es/reducers/orderedReducer'>;
}
declare module 'redux-firestore/es/reducers/queriesReducer.js' {
  declare module.exports: $Exports<'redux-firestore/es/reducers/queriesReducer'>;
}
declare module 'redux-firestore/es/reducers/statusReducer.js' {
  declare module.exports: $Exports<'redux-firestore/es/reducers/statusReducer'>;
}
declare module 'redux-firestore/es/utils/actions.js' {
  declare module.exports: $Exports<'redux-firestore/es/utils/actions'>;
}
declare module 'redux-firestore/es/utils/query.js' {
  declare module.exports: $Exports<'redux-firestore/es/utils/query'>;
}
declare module 'redux-firestore/es/utils/reducers.js' {
  declare module.exports: $Exports<'redux-firestore/es/utils/reducers'>;
}
declare module 'redux-firestore/lib/actions/firestore.js' {
  declare module.exports: $Exports<'redux-firestore/lib/actions/firestore'>;
}
declare module 'redux-firestore/lib/actions/index.js' {
  declare module.exports: $Exports<'redux-firestore/lib/actions/index'>;
}
declare module 'redux-firestore/lib/constants.js' {
  declare module.exports: $Exports<'redux-firestore/lib/constants'>;
}
declare module 'redux-firestore/lib/createFirestoreInstance.js' {
  declare module.exports: $Exports<'redux-firestore/lib/createFirestoreInstance'>;
}
declare module 'redux-firestore/lib/enhancer.js' {
  declare module.exports: $Exports<'redux-firestore/lib/enhancer'>;
}
declare module 'redux-firestore/lib/index.js' {
  declare module.exports: $Exports<'redux-firestore/lib/index'>;
}
declare module 'redux-firestore/lib/middleware.js' {
  declare module.exports: $Exports<'redux-firestore/lib/middleware'>;
}
declare module 'redux-firestore/lib/reducer.js' {
  declare module.exports: $Exports<'redux-firestore/lib/reducer'>;
}
declare module 'redux-firestore/lib/reducers/crossSliceReducer.js' {
  declare module.exports: $Exports<'redux-firestore/lib/reducers/crossSliceReducer'>;
}
declare module 'redux-firestore/lib/reducers/dataReducer.js' {
  declare module.exports: $Exports<'redux-firestore/lib/reducers/dataReducer'>;
}
declare module 'redux-firestore/lib/reducers/errorsReducer.js' {
  declare module.exports: $Exports<'redux-firestore/lib/reducers/errorsReducer'>;
}
declare module 'redux-firestore/lib/reducers/index.js' {
  declare module.exports: $Exports<'redux-firestore/lib/reducers/index'>;
}
declare module 'redux-firestore/lib/reducers/listenersReducer.js' {
  declare module.exports: $Exports<'redux-firestore/lib/reducers/listenersReducer'>;
}
declare module 'redux-firestore/lib/reducers/orderedReducer.js' {
  declare module.exports: $Exports<'redux-firestore/lib/reducers/orderedReducer'>;
}
declare module 'redux-firestore/lib/reducers/queriesReducer.js' {
  declare module.exports: $Exports<'redux-firestore/lib/reducers/queriesReducer'>;
}
declare module 'redux-firestore/lib/reducers/statusReducer.js' {
  declare module.exports: $Exports<'redux-firestore/lib/reducers/statusReducer'>;
}
declare module 'redux-firestore/lib/utils/actions.js' {
  declare module.exports: $Exports<'redux-firestore/lib/utils/actions'>;
}
declare module 'redux-firestore/lib/utils/query.js' {
  declare module.exports: $Exports<'redux-firestore/lib/utils/query'>;
}
declare module 'redux-firestore/lib/utils/reducers.js' {
  declare module.exports: $Exports<'redux-firestore/lib/utils/reducers'>;
}
declare module 'redux-firestore/src/actions/firestore.js' {
  declare module.exports: $Exports<'redux-firestore/src/actions/firestore'>;
}
declare module 'redux-firestore/src/actions/index.js' {
  declare module.exports: $Exports<'redux-firestore/src/actions/index'>;
}
declare module 'redux-firestore/src/constants.js' {
  declare module.exports: $Exports<'redux-firestore/src/constants'>;
}
declare module 'redux-firestore/src/createFirestoreInstance.js' {
  declare module.exports: $Exports<'redux-firestore/src/createFirestoreInstance'>;
}
declare module 'redux-firestore/src/enhancer.js' {
  declare module.exports: $Exports<'redux-firestore/src/enhancer'>;
}
declare module 'redux-firestore/src/index.js' {
  declare module.exports: $Exports<'redux-firestore/src/index'>;
}
declare module 'redux-firestore/src/middleware.js' {
  declare module.exports: $Exports<'redux-firestore/src/middleware'>;
}
declare module 'redux-firestore/src/reducer.js' {
  declare module.exports: $Exports<'redux-firestore/src/reducer'>;
}
declare module 'redux-firestore/src/reducers/crossSliceReducer.js' {
  declare module.exports: $Exports<'redux-firestore/src/reducers/crossSliceReducer'>;
}
declare module 'redux-firestore/src/reducers/dataReducer.js' {
  declare module.exports: $Exports<'redux-firestore/src/reducers/dataReducer'>;
}
declare module 'redux-firestore/src/reducers/errorsReducer.js' {
  declare module.exports: $Exports<'redux-firestore/src/reducers/errorsReducer'>;
}
declare module 'redux-firestore/src/reducers/index.js' {
  declare module.exports: $Exports<'redux-firestore/src/reducers/index'>;
}
declare module 'redux-firestore/src/reducers/listenersReducer.js' {
  declare module.exports: $Exports<'redux-firestore/src/reducers/listenersReducer'>;
}
declare module 'redux-firestore/src/reducers/orderedReducer.js' {
  declare module.exports: $Exports<'redux-firestore/src/reducers/orderedReducer'>;
}
declare module 'redux-firestore/src/reducers/queriesReducer.js' {
  declare module.exports: $Exports<'redux-firestore/src/reducers/queriesReducer'>;
}
declare module 'redux-firestore/src/reducers/statusReducer.js' {
  declare module.exports: $Exports<'redux-firestore/src/reducers/statusReducer'>;
}
declare module 'redux-firestore/src/utils/actions.js' {
  declare module.exports: $Exports<'redux-firestore/src/utils/actions'>;
}
declare module 'redux-firestore/src/utils/query.js' {
  declare module.exports: $Exports<'redux-firestore/src/utils/query'>;
}
declare module 'redux-firestore/src/utils/reducers.js' {
  declare module.exports: $Exports<'redux-firestore/src/utils/reducers'>;
}
