// flow-typed signature: 6a78e08b3cef3ca3fb2dcdc1abc6903f
// flow-typed version: <<STUB>>/smart-truncate_v^1.0.1/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'smart-truncate'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'smart-truncate' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'smart-truncate/dist/smart-truncate.es5' {
  declare module.exports: any;
}

declare module 'smart-truncate/src/smart-truncate' {
  declare module.exports: any;
}

declare module 'smart-truncate/src/smart-truncate.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'smart-truncate/dist/smart-truncate.es5.js' {
  declare module.exports: $Exports<'smart-truncate/dist/smart-truncate.es5'>;
}
declare module 'smart-truncate/src/smart-truncate.js' {
  declare module.exports: $Exports<'smart-truncate/src/smart-truncate'>;
}
declare module 'smart-truncate/src/smart-truncate.spec.js' {
  declare module.exports: $Exports<'smart-truncate/src/smart-truncate.spec'>;
}
