export default {
  ADD_ITEM_SUCCESS: 'ADD_ITEM_SUCCESS',
  SELL_ITEM: 'SELL_ITEM',
  ERROR: 'ERROR',
  LOGIN_ERROR: 'LOGIN_ERROR',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  SIGNOUT_SUCCESS: 'SIGNOUT_SUCCESS',
}
