export default {
  LOGIN_ERROR: 'LOGIN_ERROR',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  SIGNOUT_SUCCESS: 'SIGNOUT_SUCCESS',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_ERROR: 'SIGNUP_ERROR',
  SHOP_SIGNUP_SUCCESS: 'SHOP_SIGNUP_SUCCESS',
  SHOP_SIGNUP_ERROR: 'SHOP_SIGNUP_ERROR',
  UPDATE_DAIWALLET_BALANCE: 'UPDATE_DAIWALLET_BALANCE',
  UPDATE_XDAIWALLET_BALANCE: 'UPDATE_XDAIWALLET_BALANCE',
  UPDATE_WALLET_ADDRESS_SUCCESS: 'UPDATE_WALLET_ADDRESS_SUCCESS',
  UPDATE_WALLET_ADDRESS_ERROR: 'UPDATE_WALLET_ADDRESS_ERROR',
}
